services:
  search:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: search_subgraph
    ports:
      - "4003:4003"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
